name: pyinstaller
on: 
  workflow_dispatch:

jobs:
  build-on-windows:
    runs-on: windows-2022
    steps:
       - name: checkout code
         uses: actions/checkout@v3
         ### since windows 2022 默认已经安装了好了python和pip，所以在steps这里我们不用再去安装python和pip，直接install pyinstaller
       - name: install pyinstaller 
         run: pip install pyinstaller
       - name: build python scripts to exe
         run: pyinstaller sha256.py -F
       - name: upload exe file
         uses: actions/upload-artifact@v3
         with:
           name: sha256-windows-exe
           path: dist/sha256.exe
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: build python scripts to bin file
        run: pyinstaller sha256.py -F
      - name: upload bin file
        uses: actions/upload-artifact@v3
        with:
          name: sha256-linux-bin-file
          path: dist/sha256
  build-on-macos:
    runs-on: macos-12
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install pyinstaller
        run: pip3 install pyinstaller
      - name: build python scripts to bin file
        run: pyinstaller sha256.py -F
      - name: upload bin file
        uses: actions/upload-artifact@v3
        with:
          name: sha256-mac-bin-file
          path: dist/sha256
          
    test-build-windows:
        runs-on: windows-2022
        needs: build-on-windows
        steps:
          - name: download exe file
            uses: actions/download-artifact@v3
            with:
              name: sha256-windows-exe
          - name: test exe file
            run: |
             ls
             ./sha256.exe sha256.exe
    test-build-linux:
        runs-on: ubuntu-latest
        needs: build-on-linux
        steps:
          - name: download linux bin file
            uses: actions/download-artifact@v3
            with:
              name: sha256-linux-bin-file
          - name: test bin file
            run: |
             ls
             chmod a+x sha256
             ./sha256 sha256
    test-build-macos:
        runs-on: macos-12
        needs: build-on-macos
        steps:
          - name: download macos bin file
            uses: actions/download-artifact@v3
            with:
              name: sha256-macos-bin-file
          - name: test bin file
            run: |
             ls
             chmod a+x sha256
             ./sha256 sha256

            

        