name: pyinstaller
on: workflow_dispatch

jobs:
  build-on-windows:
    runs-on: windows-2022
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: build exe
        run: pyinstaller.exe sha256.py -F
      - name: upload exe file
        uses: actions/upload-artifact@v4
        with:
          name: sha256-windows-exe
          path: dist/sha256.exe
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
       - name: checkout code
         uses: actions/checkout@v4
       - name: install pyinstaller
         run: pip install pyinstaller
       - name: build sha256 biniary file
         run: pyinstaller sha256.py -F
       - name: upload biniary file 
         uses: actions/upload-artifact@v4
         with:
            name: sha256-linux-bin-file
            path: dist/sha256
  build-on-mac:
    runs-on: macos-12
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: install pyinstaller
        run: pip3 install pyinstaller
      - name: build binary file
        run: pyinstaller sha256.py -F
      - name: upload binary file
        uses: actions/upload-artifact@v4
        with: 
          name: sha256-macos

  test-build-windows:
    runs-on: windows-2022
    if: ${{ success() }}
    needs: [build-on-windows]
    steps:
      - name: download exe file
        uses: actions/download-artifact@v4
        with:
          name: sha256-windows-exe
      - name: test exe file
        run: |
          ls
          ./sha256.exe sha256.exe    
            path: dist/sha256
  
        
