name: workflow_secrets
on:
  workflow_dispatch
env:
  DB_U: ${{ secret.DB_USERNAME }}
  DB_P: ${{ secret.DB_PASSWORD }}
jobs:
  test-secrets:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: check env u
        run: echo "u=${{ env.DB_U }}"
      - name: check env p
        run: echo "p=${{ env.DB_P }}"
